;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 2.0.7
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :gecodecl)



(cl:defconstant _GECODEGLUE_H 1)

(cffi:defcfun ("gecode_varargs_create" gecode_varargs_create) :pointer
  (n :int))

(cffi:defcfun ("gecode_varargs_set" gecode_varargs_set) :void
  (v :pointer)
  (i :int)
  (e intvar-type))

(cffi:defcfun ("gecode_varargs_delete" gecode_varargs_delete) :void
  (v :pointer))

(cffi:defcfun ("gecode_intargs_create" gecode_intargs_create) :pointer
  (n :int))

(cffi:defcfun ("gecode_intargs_set" gecode_intargs_set) :void
  (v :pointer)
  (i :int)
  (e :int))

(cffi:defcfun ("gecode_intargs_adr" gecode_intargs_adr) :pointer
  (v :pointer))

(cffi:defcfun ("gecode_intargs_delete" gecode_intargs_delete) :void
  (v :pointer))

(cffi:defcfun ("gecode_init_exceptionHandler" gecode_init_exceptionHandler) :void
  (fptr :pointer))

(cffi:defcfun ("gecode_init_callbackInt" gecode_init_callbackInt) :void
  (fptr :pointer))

(cffi:defcfun ("gecode_intClChannel" gecode_intClChannel) :void
  (space space-type)
  (x0 size)
  (idx :unsigned-int))

(cffi:defcfun ("gecode_space_create" gecode_space_create) :pointer)

(cffi:defcfun ("gecode_space_delete" gecode_space_delete) :void
  (space space-type))

(cffi:defcfun ("gecode_space_copy" gecode_space_copy) :pointer
  (space space-type))

(cffi:defcfun ("gecode_bool_addvar" gecode_bool_addvar) size
  (space space-type))

(cffi:defcfun ("gecode_int_addvar" gecode_int_addvar) size
  (space space-type)
  (min :int)
  (max :int))

(cffi:defcfun ("gecode_float_addvar" gecode_float_addvar) size
  (space space-type)
  (min :double)
  (max :double))

(cffi:defcfun ("gecode_get_boolvar_by_index" gecode_get_boolvar_by_index) :pointer
  (space space-type)
  (index size))

(cffi:defcfun ("gecode_get_intvar_by_index" gecode_get_intvar_by_index) :pointer
  (space space-type)
  (index size))

(cffi:defcfun ("gecode_get_floatvar_by_index" gecode_get_floatvar_by_index) :pointer
  (space space-type)
  (index size))

(cffi:defcfun ("gecode_get_bool_info" gecode_get_bool_info) variable-status
  (space space-type)
  (var size)
  (value :pointer))

(cffi:defcfun ("gecode_get_int_info" gecode_get_int_info) variable-status
  (space space-type)
  (var intvar-type)
  (min :pointer)
  (max :pointer)
  (size :pointer))

(cffi:defcfun ("gecode_get_float_info" gecode_get_float_info) variable-status
  (space space-type)
  (var size)
  (min :pointer)
  (max :pointer)
  (median :pointer))

(cffi:defcfun ("gecode_branch_int_var" gecode_branch_int_var) :void
  (space space-type)
  (var size)
  (val :pointer))

(cffi:defcfun ("gecode_branch_int_vars" gecode_branch_int_vars) :void
  (space space-type)
  (vars :pointer)
  (count size)
  (var :pointer)
  (val :pointer))

(cffi:defcfun ("gecode_branch_bool_var" gecode_branch_bool_var) :void
  (space space-type)
  (var size)
  (val :pointer))

(cffi:defcfun ("gecode_branch_bool_vars" gecode_branch_bool_vars) :void
  (space space-type)
  (vars :pointer)
  (count size)
  (var :pointer)
  (val :pointer))

(cffi:defcfun ("INT_VAR_NONE" INT_VAR_NONE) :pointer)

(cffi:defcfun ("INT_VAR_RND" INT_VAR_RND) :pointer
  (seed :unsigned-int))

(cffi:defcfun ("INT_VAR_DEGREE_MIN" INT_VAR_DEGREE_MIN) :pointer)

(cffi:defcfun ("INT_VAR_DEGREE_MAX" INT_VAR_DEGREE_MAX) :pointer)

(cffi:defcfun ("INT_VAR_AFC_MIN" INT_VAR_AFC_MIN) :pointer)

(cffi:defcfun ("INT_VAR_AFC_MAX" INT_VAR_AFC_MAX) :pointer)

(cffi:defcfun ("INT_VAR_MIN_MIN" INT_VAR_MIN_MIN) :pointer)

(cffi:defcfun ("INT_VAR_MIN_MAX" INT_VAR_MIN_MAX) :pointer)

(cffi:defcfun ("INT_VAR_MAX_MIN" INT_VAR_MAX_MIN) :pointer)

(cffi:defcfun ("INT_VAR_MAX_MAX" INT_VAR_MAX_MAX) :pointer)

(cffi:defcfun ("INT_VAR_SIZE_MIN" INT_VAR_SIZE_MIN) :pointer)

(cffi:defcfun ("INT_VAR_SIZE_MAX" INT_VAR_SIZE_MAX) :pointer)

(cffi:defcfun ("INT_VAR_SIZE_DEGREE_MIN" INT_VAR_SIZE_DEGREE_MIN) :pointer)

(cffi:defcfun ("INT_VAR_SIZE_DEGREE_MAX" INT_VAR_SIZE_DEGREE_MAX) :pointer)

(cffi:defcfun ("INT_VAR_SIZE_AFC_MIN" INT_VAR_SIZE_AFC_MIN) :pointer)

(cffi:defcfun ("INT_VAR_SIZE_AFC_MAX" INT_VAR_SIZE_AFC_MAX) :pointer)

(cffi:defcfun ("INT_VAR_REGRET_MIN_MIN" INT_VAR_REGRET_MIN_MIN) :pointer)

(cffi:defcfun ("INT_VAR_REGRET_MIN_MAX" INT_VAR_REGRET_MIN_MAX) :pointer)

(cffi:defcfun ("INT_VAR_REGRET_MAX_MIN" INT_VAR_REGRET_MAX_MIN) :pointer)

(cffi:defcfun ("INT_VAR_REGRET_MAX_MAX" INT_VAR_REGRET_MAX_MAX) :pointer)

(cffi:defcfun ("INT_VAL_MIN" INT_VAL_MIN) :pointer)

(cffi:defcfun ("INT_VAL_MED" INT_VAL_MED) :pointer)

(cffi:defcfun ("INT_VAL_MAX" INT_VAL_MAX) :pointer)

(cffi:defcfun ("INT_VAL_RND" INT_VAL_RND) :pointer
  (seed :unsigned-int))

(cffi:defcfun ("INT_VAL_SPLIT_MIN" INT_VAL_SPLIT_MIN) :pointer)

(cffi:defcfun ("INT_VAL_SPLIT_MAX" INT_VAL_SPLIT_MAX) :pointer)

(cffi:defcfun ("INT_VAL_RANGE_MIN" INT_VAL_RANGE_MIN) :pointer)

(cffi:defcfun ("INT_VAL_RANGE_MAX" INT_VAL_RANGE_MAX) :pointer)

(cffi:defcfun ("INT_VALUES_MIN" INT_VALUES_MIN) :pointer)

(cffi:defcfun ("INT_VALUES_MAX" INT_VALUES_MAX) :pointer)

(cffi:defcfun ("gecode_dfs_engine_create" gecode_dfs_engine_create) :pointer
  (space space-type))

(cffi:defcfun ("gecode_dfs_engine_delete" gecode_dfs_engine_delete) :void
  (dfs search-type))

(cffi:defcfun ("gecode_dfs_engine_next" gecode_dfs_engine_next) :pointer
  (dfs search-type))

(cffi:defcfun ("gecode_bab_engine_create" gecode_bab_engine_create) :pointer
  (space space-type)
  (minVar size))

(cffi:defcfun ("gecode_bab_engine_delete" gecode_bab_engine_delete) :void
  (bab search-type))

(cffi:defcfun ("gecode_bab_engine_next" gecode_bab_engine_next) :pointer
  (bab search-type))

(cffi:defcfun ("gecode_rel_bvar_int" gecode_rel_bvar_int) :void
  (space space-type)
  (op int-relation-type)
  (v size)
  (value :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_bvar_bvar" gecode_rel_bvar_bvar) :void
  (space space-type)
  (op int-relation-type)
  (v1 size)
  (v2 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_bvar_int_reified" gecode_rel_bvar_int_reified) :void
  (space space-type)
  (op int-relation-type)
  (v1 size)
  (val :int)
  (mode reify-mode)
  (v2 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_bvar_bvar_reified" gecode_rel_bvar_bvar_reified) :void
  (space space-type)
  (op int-relation-type)
  (v1 size)
  (v2 size)
  (mode reify-mode)
  (b1 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_bvars" gecode_rel_bvars) :void
  (space space-type)
  (op int-relation-type)
  (v :pointer)
  (count size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_bvars_int" gecode_rel_bvars_int) :void
  (space space-type)
  (op int-relation-type)
  (v :pointer)
  (count size)
  (value :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_bvars_bvars" gecode_rel_bvars_bvars) :void
  (space space-type)
  (op int-relation-type)
  (v1 :pointer)
  (count1 size)
  (v2 :pointer)
  (count2 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_op_bvar_bvar_bvar" gecode_op_bvar_bvar_bvar) :void
  (space space-type)
  (op bool-operation-type)
  (v1 size)
  (v2 size)
  (b1 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_op_bvar_bvar_int" gecode_op_bvar_bvar_int) :void
  (space space-type)
  (op bool-operation-type)
  (v1 size)
  (v2 size)
  (n :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_op_bvars_int" gecode_op_bvars_int) :void
  (space space-type)
  (op bool-operation-type)
  (v :pointer)
  (count size)
  (value :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_op_bvars_bvar" gecode_op_bvars_bvar) :void
  (space space-type)
  (op bool-operation-type)
  (v :pointer)
  (count size)
  (var :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_clause_bvars_bvars_int" gecode_clause_bvars_bvars_int) :void
  (space space-type)
  (op bool-operation-type)
  (v1 :pointer)
  (count1 size)
  (v2 :pointer)
  (count2 size)
  (n :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_clause_bvars_bvars_bvar" gecode_clause_bvars_bvars_bvar) :void
  (space space-type)
  (op bool-operation-type)
  (v1 :pointer)
  (count1 size)
  (v2 :pointer)
  (count2 size)
  (bvar :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_ivar_int" gecode_rel_ivar_int) :void
  (space space-type)
  (op int-relation-type)
  (v size)
  (value :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_ivar_ivar" gecode_rel_ivar_ivar) :void
  (space space-type)
  (op int-relation-type)
  (v1 size)
  (v2 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_ivar_int_reified" gecode_rel_ivar_int_reified) :void
  (space space-type)
  (op int-relation-type)
  (v1 size)
  (val :int)
  (mode reify-mode)
  (b1 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_ivar_ivar_reified" gecode_rel_ivar_ivar_reified) :void
  (space space-type)
  (op int-relation-type)
  (v1 size)
  (v2 size)
  (mode reify-mode)
  (b1 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_ivars" gecode_rel_ivars) :void
  (space space-type)
  (op int-relation-type)
  (v :pointer)
  (count size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_ivars_int" gecode_rel_ivars_int) :void
  (space space-type)
  (op int-relation-type)
  (v :pointer)
  (count size)
  (value :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_rel_ivars_ivars" gecode_rel_ivars_ivars) :void
  (space space-type)
  (op int-relation-type)
  (v1 :pointer)
  (count1 size)
  (v2 :pointer)
  (count2 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_dst_ivars" gecode_dst_ivars) :void
  (space space-type)
  (va intvarargs-type)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_dst_ints_ivars" gecode_dst_ints_ivars) :void
  (space space-type)
  (ia intargs-type)
  (va intvarargs-type)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_distinct_ivars" gecode_distinct_ivars) :void
  (space space-type)
  (vars :pointer)
  (count size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_distinct_ints_ivars" gecode_distinct_ints_ivars) :void
  (space space-type)
  (intoffsets :pointer)
  (vars :pointer)
  (count size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_sorted_ivars_ivars" gecode_sorted_ivars_ivars) :void
  (space space-type)
  (xvars :pointer)
  (yvars :pointer)
  (count size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_sorted_ivars_ivars_ivars" gecode_sorted_ivars_ivars_ivars) :void
  (space space-type)
  (xvars :pointer)
  (yvars :pointer)
  (zvars :pointer)
  (count size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_channel_ivars_ivars" gecode_channel_ivars_ivars) :void
  (space space-type)
  (v1 :pointer)
  (v2 :pointer)
  (count size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_channel_ivars_int_ivars_int" gecode_channel_ivars_int_ivars_int) :void
  (space space-type)
  (v1 :pointer)
  (xoff :int)
  (v2 :pointer)
  (yoff :int)
  (count size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_channel_bvar_ivar" gecode_channel_bvar_ivar) :void
  (space space-type)
  (bvar size)
  (ivar size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_channel_ivar_bvar" gecode_channel_ivar_bvar) :void
  (space space-type)
  (ivar size)
  (bvar size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_channel_bvars_ivar_int" gecode_channel_bvars_ivar_int) :void
  (space space-type)
  (v1 :pointer)
  (count size)
  (ivar size)
  (offset :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_min_ivar_ivar_ivar" gecode_min_ivar_ivar_ivar) :void
  (space space-type)
  (x1 size)
  (x2 size)
  (ret size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_min_ivars_ivar" gecode_min_ivars_ivar) :void
  (space space-type)
  (v :pointer)
  (count size)
  (y :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_max_ivar_ivar_ivar" gecode_max_ivar_ivar_ivar) :void
  (space space-type)
  (x1 size)
  (x2 size)
  (ret size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_max_ivars_ivar" gecode_max_ivars_ivar) :void
  (space space-type)
  (v :pointer)
  (count size)
  (y :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_abs_ivar_ivar" gecode_abs_ivar_ivar) :void
  (space space-type)
  (x1 size)
  (x2 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_mul_ivar_ivar_ivar" gecode_mul_ivar_ivar_ivar) :void
  (space space-type)
  (x1 size)
  (x2 size)
  (ret size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_sqr_ivar_ivar" gecode_sqr_ivar_ivar) :void
  (space space-type)
  (x1 size)
  (x2 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_sqrt_ivar_ivar" gecode_sqrt_ivar_ivar) :void
  (space space-type)
  (x1 size)
  (x2 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_divmod_ivar_ivar_ivar_ivar" gecode_divmod_ivar_ivar_ivar_ivar) :void
  (space space-type)
  (x0 size)
  (x1 size)
  (x2 size)
  (x3 size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_div_ivar_ivar_ivar" gecode_div_ivar_ivar_ivar) :void
  (space space-type)
  (x1 size)
  (x2 size)
  (ret size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_mod_ivar_ivar_ivar" gecode_mod_ivar_ivar_ivar) :void
  (space space-type)
  (x1 size)
  (x2 size)
  (ret size)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ivars_int" gecode_lin_ivars_int) :void
  (space space-type)
  (rel int-relation-type)
  (v :pointer)
  (count size)
  (value :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ivars_ivar" gecode_lin_ivars_ivar) :void
  (space space-type)
  (rel int-relation-type)
  (v :pointer)
  (count size)
  (var :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ivars_int_reified" gecode_lin_ivars_int_reified) :void
  (space space-type)
  (rel int-relation-type)
  (v :pointer)
  (count size)
  (value :int)
  (mode reify-mode)
  (bvar :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ivars_ivar_reified" gecode_lin_ivars_ivar_reified) :void
  (space space-type)
  (rel int-relation-type)
  (v :pointer)
  (count size)
  (var :int)
  (mode reify-mode)
  (bvar :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ints_ivars_int" gecode_lin_ints_ivars_int) :void
  (space space-type)
  (rel int-relation-type)
  (ints :pointer)
  (v :pointer)
  (count size)
  (value :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ints_ivars_ivar" gecode_lin_ints_ivars_ivar) :void
  (space space-type)
  (rel int-relation-type)
  (ints :pointer)
  (v :pointer)
  (count size)
  (var :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ints_ivars_int_reified" gecode_lin_ints_ivars_int_reified) :void
  (space space-type)
  (rel int-relation-type)
  (ints :pointer)
  (v :pointer)
  (count size)
  (value :int)
  (mode reify-mode)
  (bvar :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ints_ivars_ivar_reified" gecode_lin_ints_ivars_ivar_reified) :void
  (space space-type)
  (rel int-relation-type)
  (ints :pointer)
  (v :pointer)
  (count size)
  (var :int)
  (mode reify-mode)
  (bvar :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_bvars_int" gecode_lin_bvars_int) :void
  (space space-type)
  (rel int-relation-type)
  (v :pointer)
  (count size)
  (value :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_bvars_ivar" gecode_lin_bvars_ivar) :void
  (space space-type)
  (rel int-relation-type)
  (v :pointer)
  (count size)
  (var :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_bvars_int_reified" gecode_lin_bvars_int_reified) :void
  (space space-type)
  (rel int-relation-type)
  (v :pointer)
  (count size)
  (value :int)
  (mode reify-mode)
  (bvar :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_bvars_ivar_reified" gecode_lin_bvars_ivar_reified) :void
  (space space-type)
  (rel int-relation-type)
  (v :pointer)
  (count size)
  (var :int)
  (mode reify-mode)
  (bvar :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ints_bvars_int" gecode_lin_ints_bvars_int) :void
  (space space-type)
  (rel int-relation-type)
  (ints :pointer)
  (v :pointer)
  (count size)
  (value :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ints_bvars_ivar" gecode_lin_ints_bvars_ivar) :void
  (space space-type)
  (rel int-relation-type)
  (ints :pointer)
  (v :pointer)
  (count size)
  (var :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ints_bvars_int_reified" gecode_lin_ints_bvars_int_reified) :void
  (space space-type)
  (rel int-relation-type)
  (ints :pointer)
  (v :pointer)
  (count size)
  (value :int)
  (mode reify-mode)
  (bvar :int)
  (icl int-consistency-level))

(cffi:defcfun ("gecode_lin_ints_bvars_ivar_reified" gecode_lin_ints_bvars_ivar_reified) :void
  (space space-type)
  (rel int-relation-type)
  (ints :pointer)
  (v :pointer)
  (count size)
  (var :int)
  (mode reify-mode)
  (bvar :int)
  (icl int-consistency-level))


